name: CI Workflow  # Name of the workflow

"on":  # Define the events that trigger the workflow
  push:
    branches:
      - mine_repository
  pull_request:
    branches:
      - mine_repository

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        
    defaults:
      run:
        working-directory: ci_lab # Set the default working directory for all steps

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python ${{ matrix.python-version }} 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  # Ensure consistency in Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with Pytest
        run: pytest --cov=src --cov-report=term-missing

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8 Linting
        run: flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics